config/routes.rb
Rails.application.routes.draw do
  resources :vital_records
  resources :visiting_schedules
  resources :patients
  resources :nurses

  get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')

end

app/models/visiting_schedule.rb
class VisitingSchedule < ActiveRecord::Base
  belongs_to :nurse
  belongs_to :patient

  def self.by_nurse_id_and_appointment_time(nurse_id = nil, appointment_time = nil)
    return where(nurse_id: nurse_id, appointment_time: get_full_day(appointment_time)) if nurse_id && appointment_time
    return where(nurse_id: nurse_id) if nurse_id && !appointment_time
    return where(appointment_time: get_full_day(appointment_time)) if !nurse_id && appointment_time
    all
  end

  private
    def self.get_full_day(date)
      date.to_datetime.in_time_zone("Asia/Singapore").beginning_of_day..date.to_datetime.in_time_zone("Asia/Singapore").end_of_day
    end
end

app/controllers/visiting_schedules_controller.rb
class VisitingSchedulesController < ApplicationController
  before_action :set_visiting_schedule, only: [:show, :edit, :update, :destroy]

  # GET /visiting_schedules
  # GET /visiting_schedules.json
  def index
    # if params[:nurse_id].nil?
    #   @visiting_schedules = VisitingSchedule.all
    #
    # else
    #   @visiting_schedules= VisitingSchedule.where(nurse_id: params[:nurse_id])
    # end

    # if params.nil?
    #   @visiting_schedules = VisitingSchedule.all
    #   return
    # end

    #@visiting_schedules= [VisitingSchedule.where(:all, :conditions => params[:nurse_id])]
    #where('user_id = :user_id AND post_id = :post_id', params)
    @visiting_schedules = VisitingSchedule.by_nurse_id_and_appointment_time(params[:nurse_id], params[:appointment_time])

  end

  # GET /visiting_schedules/1
  # GET /visiting_schedules/1.json
  def show
  end

  # GET /visiting_schedules/new
  def new
    @visiting_schedule = VisitingSchedule.new
  end

  # GET /visiting_schedules/1/edit
  def edit
  end

  # POST /visiting_schedules
  # POST /visiting_schedules.json
  def create
    @visiting_schedule = VisitingSchedule.new(visiting_schedule_params)

    respond_to do |format|
      if @visiting_schedule.save
        format.html { redirect_to @visiting_schedule, notice: 'Visiting schedule was successfully created.' }
        format.json { render :show, status: :created, location: @visiting_schedule }
      else
        format.html { render :new }
        format.json { render json: @visiting_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visiting_schedules/1
  # PATCH/PUT /visiting_schedules/1.json
  def update
    respond_to do |format|
      if @visiting_schedule.update(visiting_schedule_params)
        format.html { redirect_to @visiting_schedule, notice: 'Visiting schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @visiting_schedule }
      else
        format.html { render :edit }
        format.json { render json: @visiting_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visiting_schedules/1
  # DELETE /visiting_schedules/1.json
  def destroy
    @visiting_schedule.destroy
    respond_to do |format|
      format.html { redirect_to visiting_schedules_url, notice: 'Visiting schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visiting_schedule
      @visiting_schedule = VisitingSchedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visiting_schedule_params
      params.require(:visiting_schedule).permit(:appointment_time, :nurse_id, :patient_id)
    end
end

app/helpers/visiting_schedules_helper.rb
module VisitingSchedulesHelper
end

app/views/visiting_schedules/_form.html.erb
<%= form_for(@visiting_schedule) do |f| %>
  <% if @visiting_schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visiting_schedule.errors.count, "error") %> prohibited this visiting_schedule from being saved:</h2>

      <ul>
      <% @visiting_schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :appointment_time %><br>
    <%= f.datetime_select :appointment_time %>
  </div>
  <div class="field">
    <%= f.label :nurse_id %><br>
    <%= f.text_field :nurse_id %>
  </div>
  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.text_field :patient_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visiting_schedules/edit.html.erb
<h1>Editing Visiting Schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @visiting_schedule %> |
<%= link_to 'Back', visiting_schedules_path %>

app/views/visiting_schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Visiting Schedules</h1>

<table>
  <thead>
    <tr>
      <th>Nurse id</th>
      <th>Patient ids</th>
      <th>Appointment time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visiting_schedules.each do |visiting_schedule| %>
      <tr>
        <td><%= visiting_schedule.nurse_id %></td>
        <td><%= visiting_schedule.patient_id %></td>
        <td><%= visiting_schedule.appointment_time %></td>
        <td><%= link_to 'Show', visiting_schedule %></td>
        <td><%= link_to 'Edit', edit_visiting_schedule_path(visiting_schedule) %></td>
        <td><%= link_to 'Destroy', visiting_schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visiting schedule', new_visiting_schedule_path %>

app/views/visiting_schedules/new.html.erb
<h1>New Visiting Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', visiting_schedules_path %>

app/views/visiting_schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Appointment time:</strong>
  <%= @visiting_schedule.appointment_time %>
  <strong>Nurse id:</strong>
  <%= @visiting_schedule.nurse_id %>
  <strong>Patient id:</strong>
  <%= @visiting_schedule.patient_id %>
</p>

<%= link_to 'Edit', edit_visiting_schedule_path(@visiting_schedule) %> |
<%= link_to 'Back', visiting_schedules_path %>