config/routes.rb
Rails.application.routes.draw do
  resources :vital_records
  resources :visiting_schedules
  resources :patients
  resources :nurses

  get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')

end

app/models/vital_record.rb
class VitalRecord < ActiveRecord::Base
end

app/controllers/vital_records_controller.rb
class VitalRecordsController < ApplicationController
  before_action :set_vital_record, only: [:show, :edit, :update, :destroy]

  # GET /vital_records
  # GET /vital_records.json
  def index
    @vital_records = VitalRecord.all
  end

  # GET /vital_records/1
  # GET /vital_records/1.json
  def show
  end

  # GET /vital_records/new
  def new
    @vital_record = VitalRecord.new
  end

  # GET /vital_records/1/edit
  def edit
  end

  # POST /vital_records
  # POST /vital_records.json
  def create
    @vital_record = VitalRecord.new(vital_record_params)

    respond_to do |format|
      if @vital_record.save
        format.html { redirect_to @vital_record, notice: 'Vital record was successfully created.' }
        format.json { render :show, status: :created, location: @vital_record }
      else
        format.html { render :new }
        format.json { render json: @vital_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vital_records/1
  # PATCH/PUT /vital_records/1.json
  def update
    respond_to do |format|
      if @vital_record.update(vital_record_params)
        format.html { redirect_to @vital_record, notice: 'Vital record was successfully updated.' }
        format.json { render :show, status: :ok, location: @vital_record }
      else
        format.html { render :edit }
        format.json { render json: @vital_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vital_records/1
  # DELETE /vital_records/1.json
  def destroy
    @vital_record.destroy
    respond_to do |format|
      format.html { redirect_to vital_records_url, notice: 'Vital record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vital_record
      @vital_record = VitalRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vital_record_params
      params.require(:vital_record).permit(:height, :weight, :pulse, :temperature, :bp_high, :bp_low, :patient_id)
    end
end

app/helpers/vital_records_helper.rb
module VitalRecordsHelper
end

app/views/vital_records/_form.html.erb
<%= form_for(@vital_record) do |f| %>
  <% if @vital_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vital_record.errors.count, "error") %> prohibited this vital_record from being saved:</h2>

      <ul>
      <% @vital_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.text_field :patient_id %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :pulse %><br>
    <%= f.number_field :pulse %>
  </div>
  <div class="field">
    <%= f.label :temperature %><br>
    <%= f.text_field :temperature %>
  </div>
  <div class="field">
    <%= f.label :bp_high %><br>
    <%= f.number_field :bp_high %>
  </div>
  <div class="field">
    <%= f.label :bp_low %><br>
    <%= f.number_field :bp_low %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vital_records/edit.html.erb
<h1>Editing Vital Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @vital_record %> |
<%= link_to 'Back', vital_records_path %>

app/views/vital_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vital Records</h1>

<table>
  <thead>
    <tr>
      <th>Patient ID</th>
      <th>Height</th>
      <th>Weight</th>
      <th>Pulse</th>
      <th>temperature</th>
      <th>Bp high</th>
      <th>Bp low</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vital_records.each do |vital_record| %>
      <tr>
        <td><%= vital_record.patient_id %></td>
        <td><%= vital_record.height %></td>
        <td><%= vital_record.weight %></td>
        <td><%= vital_record.pulse %></td>
        <td><%= vital_record.temperature %></td>
        <td><%= vital_record.bp_high %></td>
        <td><%= vital_record.bp_low %></td>
        <td><%= link_to 'Show', vital_record %></td>
        <td><%= link_to 'Edit', edit_vital_record_path(vital_record) %></td>
        <td><%= link_to 'Destroy', vital_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vital record', new_vital_record_path %>

app/views/vital_records/new.html.erb
<h1>New Vital Record</h1>

<%= render 'form' %>

<%= link_to 'Back', vital_records_path %>

app/views/vital_records/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Patient id:</strong>
  <%= @vital_record.patient_id %>
</p>

<p>
  <strong>Height:</strong>
  <%= @vital_record.height %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @vital_record.weight %>
</p>

<p>
  <strong>Pulse:</strong>
  <%= @vital_record.pulse %>
</p>

<p>
  <strong>temperature:</strong>
  <%= @vital_record.temperature %>
</p>

<p>
  <strong>Bp high:</strong>
  <%= @vital_record.bp_high %>
</p>

<p>
  <strong>Bp low:</strong>
  <%= @vital_record.bp_low %>
</p>

<%= link_to 'Edit', edit_vital_record_path(@vital_record) %> |
<%= link_to 'Back', vital_records_path %>