config/routes.rb
Rails.application.routes.draw do
  resources :vital_records
  resources :visiting_schedules
  resources :patients
  resources :nurses

  get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')

end

app/controllers/nurses_controller.rb
class NursesController < ApplicationController
  before_action :set_nurse, only: [:show, :edit, :update, :destroy]

  # GET /nurses
  # GET /nurses.json
  def index
    @nurses = Nurse.all
  end

  # GET /nurses/1
  # GET /nurses/1.json
  def show
  end

  # GET /nurses/new
  def new
    @nurse = Nurse.new
  end

  # GET /nurses/1/edit
  def edit
  end

  # POST /nurses
  # POST /nurses.json
  def create
    @nurse = Nurse.new(nurse_params)

    respond_to do |format|
      if @nurse.save
        format.html { redirect_to @nurse, notice: 'Nurse was successfully created.' }
        format.json { render :show, status: :created, location: @nurse }
      else
        format.html { render :new }
        format.json { render json: @nurse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nurses/1
  # PATCH/PUT /nurses/1.json
  def update
    respond_to do |format|
      if @nurse.update(nurse_params)
        format.html { redirect_to @nurse, notice: 'Nurse was successfully updated.' }
        format.json { render :show, status: :ok, location: @nurse }
      else
        format.html { render :edit }
        format.json { render json: @nurse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nurses/1
  # DELETE /nurses/1.json
  def destroy
    @nurse.destroy
    respond_to do |format|
      format.html { redirect_to nurses_url, notice: 'Nurse was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nurse
      @nurse = Nurse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nurse_params
      params.require(:nurse).permit(:name, :email, :password)
    end
end

app/helpers/nurses_helper.rb
module NursesHelper
end

app/views/nurses/_form.html.erb
<%= form_for(@nurse) do |f| %>
  <% if @nurse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nurse.errors.count, "error") %> prohibited this nurse from being saved:</h2>

      <ul>
      <% @nurse.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nurses/edit.html.erb
<h1>Editing Nurse</h1>

<%= render 'form' %>

<%= link_to 'Show', @nurse %> |
<%= link_to 'Back', nurses_path %>

app/views/nurses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Nurses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nurses.each do |nurse| %>
      <tr>
        <td><%= nurse.name %></td>
        <td><%= nurse.email %></td>
        <td><%= nurse.password %></td>
        <td><%= link_to 'Show', nurse %></td>
        <td><%= link_to 'Edit', edit_nurse_path(nurse) %></td>
        <td><%= link_to 'Destroy', nurse, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nurse', new_nurse_path %>

app/views/nurses/new.html.erb
<h1>New Nurse</h1>

<%= render 'form' %>

<%= link_to 'Back', nurses_path %>

app/views/nurses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @nurse.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @nurse.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @nurse.password %>
</p>

<%= link_to 'Edit', edit_nurse_path(@nurse) %> |
<%= link_to 'Back', nurses_path %>